// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type {
  Bit,
  Char,
  CodecTypes as PgTypes,
  Interval,
  JsonValue,
  Numeric,
  Time,
  TimeString,
  Timestamp,
  TimestampString,
  Timestamptz,
  TimestamptzString,
  Timetz,
  VarBit,
  Varchar,
} from '@prisma/orm-postgres/target/codec-types';
import type { QueryOperationTypes as PgTargetQueryOps } from '@prisma/orm-postgres/target/operation-types';

import type {
  ContractWithTypeMaps,
  RelationKeys,
  TypeMaps as TypeMapsType,
} from '@prisma/orm-postgres/family-contract/types';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-postgres/contract/types';

export type StorageHash =
  StorageHashBase<'3e2f892c2427f2b3e7ccf9c48bd6a89116e9afbdcc2ff177d41df4d1076103ea'>;
export type ExecutionHash =
  ExecutionHashBase<'7c4b6f095a668a42af2b7e2566d9388a92828734cdddc102a04bb5cd3c7ac2e4'>;
export type ProfileHash =
  ProfileHashBase<'3916f444a8a17ad749191acf9e08dad97d1a327b88c2f1d45d12f240296aa8b2'>;

export type CodecTypes = PgTypes;
export type LaneCodecTypes = CodecTypes;
export type QueryOperationTypes = PgTargetQueryOps<CodecTypes>;
export type AggregateTypes = {
  readonly avg: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
    };
  };
  readonly avgDecimal: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
    };
  };
  readonly count: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8number@1'; readonly nullable: false };
  };
  readonly countBigInt: {
    readonly byCodec: {};
    readonly withoutInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
    readonly anyInput: { readonly output: 'pg/int8@1'; readonly nullable: false };
  };
  readonly max: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly min: {
    readonly byCodec: {
      readonly 'pg/char@1': { readonly output: 'pg/char@1'; readonly nullable: true };
      readonly 'pg/date-string@1': { readonly output: 'pg/date-string@1'; readonly nullable: true };
      readonly 'pg/date-temporal@1': {
        readonly output: 'pg/date-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/enum@1': { readonly output: 'pg/enum@1'; readonly nullable: true };
      readonly 'pg/float@1': { readonly output: 'pg/float@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/inet@1': { readonly output: 'pg/inet@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int2@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int4@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/text-array@1': { readonly output: 'pg/text-array@1'; readonly nullable: true };
      readonly 'pg/text@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/time-string@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': {
        readonly output: 'pg/time-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-string@1': {
        readonly output: 'pg/timestamp-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamp-temporal@1': {
        readonly output: 'pg/timestamp-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-date@1': {
        readonly output: 'pg/timestamptz-date@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-string@1': {
        readonly output: 'pg/timestamptz-string@1';
        readonly nullable: true;
      };
      readonly 'pg/timestamptz-temporal@1': {
        readonly output: 'pg/timestamptz-temporal@1';
        readonly nullable: true;
      };
      readonly 'pg/timetz@1': { readonly output: 'pg/timetz@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'pg/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
      readonly 'sql/char@1': { readonly output: 'sql/char@1'; readonly nullable: true };
      readonly 'sql/float@1': { readonly output: 'sql/float@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'sql/int@1'; readonly nullable: true };
      readonly 'sql/text@1': { readonly output: 'sql/text@1'; readonly nullable: true };
      readonly 'sql/varchar@1': { readonly output: 'pg/text@1'; readonly nullable: true };
    };
  };
  readonly sum: {
    readonly byCodec: {
      readonly 'pg/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/float4@1': { readonly output: 'pg/float4@1'; readonly nullable: true };
      readonly 'pg/float8@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'pg/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
      readonly 'pg/interval@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/numeric@1': { readonly output: 'pg/numeric@1'; readonly nullable: true };
      readonly 'pg/time-string@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/time-temporal@1': { readonly output: 'pg/interval@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/float@1': { readonly output: 'pg/float8@1'; readonly nullable: true };
      readonly 'sql/int@1': { readonly output: 'pg/int8number@1'; readonly nullable: true };
    };
  };
  readonly sumBigInt: {
    readonly byCodec: {
      readonly 'pg/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int2@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int4@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
      readonly 'pg/int8@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/int8number@1': { readonly output: 'pg/unboundedint@1'; readonly nullable: true };
      readonly 'pg/unboundedint@1': {
        readonly output: 'pg/unboundedint@1';
        readonly nullable: true;
      };
      readonly 'sql/int@1': { readonly output: 'pg/int8@1'; readonly nullable: true };
    };
  };
};
type DefaultLiteralValue<CodecId extends string, Encoded> = CodecId extends keyof CodecTypes
  ? Encoded extends CodecTypes[CodecId]['json']
    ? Encoded
    : CodecTypes[CodecId]['json']
  : Encoded;

export type FieldOutputTypes = {
  readonly public: {
    readonly Attempt: {
      readonly correct: CodecTypes['pg/bool@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly freeTapsUsed: CodecTypes['pg/int4@1']['output'];
      readonly guess: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'];
      readonly reveals: CodecTypes['pg/json@1']['output'];
      readonly score: CodecTypes['pg/int4@1']['output'] | null;
      readonly sessionId: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly DailySession: {
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly ordinal: CodecTypes['pg/int4@1']['output'];
      readonly playerId: CodecTypes['pg/text@1']['output'];
      readonly score: CodecTypes['pg/int4@1']['output'] | null;
      readonly status: 'IN_PROGRESS' | 'FINISHED';
    };
    readonly Event: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly exchangeId: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'] | null;
      readonly payload: CodecTypes['pg/json@1']['output'];
      readonly playerId: CodecTypes['pg/text@1']['output'];
      readonly type: 'TAP' | 'GUESS' | 'SHARE' | 'ROUND_COMPLETE' | 'SESSION_COMPLETE';
    };
    readonly Movie: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly genre: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly runtime: CodecTypes['pg/int4@1']['output'];
      readonly status: 'DRAFT' | 'APPROVED';
      readonly tier: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly year: CodecTypes['pg/int4@1']['output'];
    };
    readonly MovieExchange: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isFixed: CodecTypes['pg/bool@1']['output'];
      readonly lines: CodecTypes['pg/json@1']['output'];
      readonly minute: CodecTypes['pg/int4@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'];
      readonly poolRank: CodecTypes['pg/int4@1']['output'] | null;
      readonly tier: 'ICONIC' | 'MEDIUM' | 'DEEPCUT';
    };
    readonly MovieOptions: {
      readonly distractors: CodecTypes['pg/json@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Player: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lastSeenAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly provider: 'GUEST' | 'GOOGLE' | 'EMAIL';
      readonly timezone: CodecTypes['pg/text@1']['output'];
    };
    readonly ScheduleEntry: {
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'];
      readonly position: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly public: {
    readonly Attempt: {
      readonly correct: CodecTypes['pg/bool@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly freeTapsUsed: CodecTypes['pg/int4@1']['input'];
      readonly guess: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'];
      readonly reveals: CodecTypes['pg/json@1']['input'];
      readonly score: CodecTypes['pg/int4@1']['input'] | null;
      readonly sessionId: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly DailySession: {
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly ordinal: CodecTypes['pg/int4@1']['input'];
      readonly playerId: CodecTypes['pg/text@1']['input'];
      readonly score: CodecTypes['pg/int4@1']['input'] | null;
      readonly status: 'IN_PROGRESS' | 'FINISHED';
    };
    readonly Event: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly exchangeId: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'] | null;
      readonly payload: CodecTypes['pg/json@1']['input'];
      readonly playerId: CodecTypes['pg/text@1']['input'];
      readonly type: 'TAP' | 'GUESS' | 'SHARE' | 'ROUND_COMPLETE' | 'SESSION_COMPLETE';
    };
    readonly Movie: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly genre: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly runtime: CodecTypes['pg/int4@1']['input'];
      readonly status: 'DRAFT' | 'APPROVED';
      readonly tier: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly year: CodecTypes['pg/int4@1']['input'];
    };
    readonly MovieExchange: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isFixed: CodecTypes['pg/bool@1']['input'];
      readonly lines: CodecTypes['pg/json@1']['input'];
      readonly minute: CodecTypes['pg/int4@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'];
      readonly poolRank: CodecTypes['pg/int4@1']['input'] | null;
      readonly tier: 'ICONIC' | 'MEDIUM' | 'DEEPCUT';
    };
    readonly MovieOptions: {
      readonly distractors: CodecTypes['pg/json@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Player: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lastSeenAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly provider: 'GUEST' | 'GOOGLE' | 'EMAIL';
      readonly timezone: CodecTypes['pg/text@1']['input'];
    };
    readonly ScheduleEntry: {
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'];
      readonly position: CodecTypes['pg/int4@1']['input'];
    };
  };
};
export type StorageColumnTypes = {
  readonly public: {
    readonly Attempt: {
      readonly correct: CodecTypes['pg/bool@1']['output'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly freeTapsUsed: CodecTypes['pg/int4@1']['output'];
      readonly guess: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'];
      readonly reveals: CodecTypes['pg/json@1']['output'];
      readonly score: CodecTypes['pg/int4@1']['output'] | null;
      readonly sessionId: CodecTypes['pg/int4@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    };
    readonly DailySession: {
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly ordinal: CodecTypes['pg/int4@1']['output'];
      readonly playerId: CodecTypes['pg/text@1']['output'];
      readonly score: CodecTypes['pg/int4@1']['output'] | null;
      readonly status: 'IN_PROGRESS' | 'FINISHED';
    };
    readonly Event: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly exchangeId: CodecTypes['pg/int4@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'] | null;
      readonly payload: CodecTypes['pg/json@1']['output'];
      readonly playerId: CodecTypes['pg/text@1']['output'];
      readonly type: 'TAP' | 'GUESS' | 'SHARE' | 'ROUND_COMPLETE' | 'SESSION_COMPLETE';
    };
    readonly Movie: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly genre: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly runtime: CodecTypes['pg/int4@1']['output'];
      readonly status: 'DRAFT' | 'APPROVED';
      readonly tier: CodecTypes['pg/int4@1']['output'];
      readonly title: CodecTypes['pg/text@1']['output'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly year: CodecTypes['pg/int4@1']['output'];
    };
    readonly MovieExchange: {
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly isFixed: CodecTypes['pg/bool@1']['output'];
      readonly lines: CodecTypes['pg/json@1']['output'];
      readonly minute: CodecTypes['pg/int4@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'];
      readonly poolRank: CodecTypes['pg/int4@1']['output'] | null;
      readonly tier: 'ICONIC' | 'MEDIUM' | 'DEEPCUT';
    };
    readonly MovieOptions: {
      readonly distractors: CodecTypes['pg/json@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'];
    };
    readonly Player: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly email: CodecTypes['pg/text@1']['output'] | null;
      readonly id: CodecTypes['pg/text@1']['output'];
      readonly lastSeenAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly provider: 'GUEST' | 'GOOGLE' | 'EMAIL';
      readonly timezone: CodecTypes['pg/text@1']['output'];
    };
    readonly ScheduleEntry: {
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['output'];
      readonly id: CodecTypes['pg/int4@1']['output'];
      readonly movieId: CodecTypes['pg/int4@1']['output'];
      readonly position: CodecTypes['pg/int4@1']['output'];
    };
  };
};
export type StorageColumnInputTypes = {
  readonly public: {
    readonly Attempt: {
      readonly correct: CodecTypes['pg/bool@1']['input'] | null;
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly freeTapsUsed: CodecTypes['pg/int4@1']['input'];
      readonly guess: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'];
      readonly reveals: CodecTypes['pg/json@1']['input'];
      readonly score: CodecTypes['pg/int4@1']['input'] | null;
      readonly sessionId: CodecTypes['pg/int4@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
    };
    readonly DailySession: {
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly finishedAt: CodecTypes['pg/timestamptz-temporal@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly ordinal: CodecTypes['pg/int4@1']['input'];
      readonly playerId: CodecTypes['pg/text@1']['input'];
      readonly score: CodecTypes['pg/int4@1']['input'] | null;
      readonly status: 'IN_PROGRESS' | 'FINISHED';
    };
    readonly Event: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly exchangeId: CodecTypes['pg/int4@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'] | null;
      readonly payload: CodecTypes['pg/json@1']['input'];
      readonly playerId: CodecTypes['pg/text@1']['input'];
      readonly type: 'TAP' | 'GUESS' | 'SHARE' | 'ROUND_COMPLETE' | 'SESSION_COMPLETE';
    };
    readonly Movie: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly genre: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly runtime: CodecTypes['pg/int4@1']['input'];
      readonly status: 'DRAFT' | 'APPROVED';
      readonly tier: CodecTypes['pg/int4@1']['input'];
      readonly title: CodecTypes['pg/text@1']['input'];
      readonly updatedAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly year: CodecTypes['pg/int4@1']['input'];
    };
    readonly MovieExchange: {
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly isFixed: CodecTypes['pg/bool@1']['input'];
      readonly lines: CodecTypes['pg/json@1']['input'];
      readonly minute: CodecTypes['pg/int4@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'];
      readonly poolRank: CodecTypes['pg/int4@1']['input'] | null;
      readonly tier: 'ICONIC' | 'MEDIUM' | 'DEEPCUT';
    };
    readonly MovieOptions: {
      readonly distractors: CodecTypes['pg/json@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'];
    };
    readonly Player: {
      readonly createdAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly email: CodecTypes['pg/text@1']['input'] | null;
      readonly id: CodecTypes['pg/text@1']['input'];
      readonly lastSeenAt: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly provider: 'GUEST' | 'GOOGLE' | 'EMAIL';
      readonly timezone: CodecTypes['pg/text@1']['input'];
    };
    readonly ScheduleEntry: {
      readonly day: CodecTypes['pg/timestamptz-temporal@1']['input'];
      readonly id: CodecTypes['pg/int4@1']['input'];
      readonly movieId: CodecTypes['pg/int4@1']['input'];
      readonly position: CodecTypes['pg/int4@1']['input'];
    };
  };
};

export namespace Models {
  export type public_Attempt = {
    correct: CodecTypes['pg/bool@1']['output'] | null;
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    finishedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    freeTapsUsed: CodecTypes['pg/int4@1']['output'];
    guess: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/int4@1']['output'];
    movieId: CodecTypes['pg/int4@1']['output'];
    reveals: CodecTypes['pg/json@1']['output'];
    score: CodecTypes['pg/int4@1']['output'] | null;
    sessionId: CodecTypes['pg/int4@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    movie: public_Movie;
    session: public_DailySession;
    readonly [RelationKeys]?: 'movie' | 'session';
  };
  export type public_DailySession = {
    day: CodecTypes['pg/timestamptz-temporal@1']['output'];
    finishedAt: CodecTypes['pg/timestamptz-temporal@1']['output'] | null;
    id: CodecTypes['pg/int4@1']['output'];
    ordinal: CodecTypes['pg/int4@1']['output'];
    playerId: CodecTypes['pg/text@1']['output'];
    score: CodecTypes['pg/int4@1']['output'] | null;
    status: 'IN_PROGRESS' | 'FINISHED';
    attempts: public_Attempt[];
    player: public_Player;
    readonly [RelationKeys]?: 'attempts' | 'player';
  };
  export type public_Event = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    day: CodecTypes['pg/timestamptz-temporal@1']['output'];
    exchangeId: CodecTypes['pg/int4@1']['output'] | null;
    id: CodecTypes['pg/int4@1']['output'];
    movieId: CodecTypes['pg/int4@1']['output'] | null;
    payload: CodecTypes['pg/json@1']['output'];
    playerId: CodecTypes['pg/text@1']['output'];
    type: 'TAP' | 'GUESS' | 'SHARE' | 'ROUND_COMPLETE' | 'SESSION_COMPLETE';
    exchange: public_MovieExchange | null;
    player: public_Player;
    readonly [RelationKeys]?: 'exchange' | 'player';
  };
  export type public_Movie = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    genre: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/int4@1']['output'];
    runtime: CodecTypes['pg/int4@1']['output'];
    status: 'DRAFT' | 'APPROVED';
    tier: CodecTypes['pg/int4@1']['output'];
    title: CodecTypes['pg/text@1']['output'];
    updatedAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    year: CodecTypes['pg/int4@1']['output'];
    attempts: public_Attempt[];
    exchanges: public_MovieExchange[];
    options: public_MovieOptions | null;
    schedule: public_ScheduleEntry[];
    readonly [RelationKeys]?: 'attempts' | 'exchanges' | 'options' | 'schedule';
  };
  export type public_MovieExchange = {
    id: CodecTypes['pg/int4@1']['output'];
    isFixed: CodecTypes['pg/bool@1']['output'];
    lines: CodecTypes['pg/json@1']['output'];
    minute: CodecTypes['pg/int4@1']['output'];
    movieId: CodecTypes['pg/int4@1']['output'];
    poolRank: CodecTypes['pg/int4@1']['output'] | null;
    tier: 'ICONIC' | 'MEDIUM' | 'DEEPCUT';
    events: public_Event[];
    movie: public_Movie;
    readonly [RelationKeys]?: 'events' | 'movie';
  };
  export type public_MovieOptions = {
    distractors: CodecTypes['pg/json@1']['output'];
    movieId: CodecTypes['pg/int4@1']['output'];
    movie: public_Movie;
    readonly [RelationKeys]?: 'movie';
  };
  export type public_Player = {
    createdAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    email: CodecTypes['pg/text@1']['output'] | null;
    id: CodecTypes['pg/text@1']['output'];
    lastSeenAt: CodecTypes['pg/timestamptz-temporal@1']['output'];
    provider: 'GUEST' | 'GOOGLE' | 'EMAIL';
    timezone: CodecTypes['pg/text@1']['output'];
    events: public_Event[];
    sessions: public_DailySession[];
    readonly [RelationKeys]?: 'events' | 'sessions';
  };
  export type public_ScheduleEntry = {
    day: CodecTypes['pg/timestamptz-temporal@1']['output'];
    id: CodecTypes['pg/int4@1']['output'];
    movieId: CodecTypes['pg/int4@1']['output'];
    position: CodecTypes['pg/int4@1']['output'];
    movie: public_Movie;
    readonly [RelationKeys]?: 'movie';
  };
}

export declare const models: {
  public: {
    Attempt: Models.public_Attempt;
    DailySession: Models.public_DailySession;
    Event: Models.public_Event;
    Movie: Models.public_Movie;
    MovieExchange: Models.public_MovieExchange;
    MovieOptions: Models.public_MovieOptions;
    Player: Models.public_Player;
    ScheduleEntry: Models.public_ScheduleEntry;
  };
};

export type TypeMaps = TypeMapsType<
  CodecTypes,
  QueryOperationTypes,
  FieldOutputTypes,
  FieldInputTypes,
  StorageColumnTypes,
  StorageColumnInputTypes,
  AggregateTypes
>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly public: {
        readonly id: 'public';
        readonly kind: 'postgres-schema';
        readonly entries: {
          readonly table: {
            readonly Attempt: {
              columns: {
                readonly correct: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: true;
                };
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly finishedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly freeTapsUsed: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 0>;
                  };
                };
                readonly guess: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly movieId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly reveals: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                };
                readonly score: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly sessionId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['sessionId', 'movieId'] }];
              indexes: readonly [
                {
                  readonly name: 'Attempt_movieId_idx_8cb9f9db';
                  readonly prefix: 'Attempt_movieId_idx';
                  readonly columns: readonly ['movieId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Attempt_sessionId_idx_29f415d4';
                  readonly prefix: 'Attempt_sessionId_idx';
                  readonly columns: readonly ['sessionId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Attempt';
                    readonly columns: readonly ['sessionId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'DailySession';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Attempt';
                    readonly columns: readonly ['movieId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Movie';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly DailySession: {
              columns: {
                readonly day: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly finishedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly ordinal: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 1>;
                  };
                };
                readonly playerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly score: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'IN_PROGRESS'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['playerId', 'day', 'ordinal'] }];
              indexes: readonly [
                {
                  readonly name: 'DailySession_playerId_day_idx_660e05ab';
                  readonly prefix: 'DailySession_playerId_day_idx';
                  readonly columns: readonly ['playerId', 'day'];
                  readonly unique: false;
                },
                {
                  readonly name: 'DailySession_playerId_idx_710cf1aa';
                  readonly prefix: 'DailySession_playerId_idx';
                  readonly columns: readonly ['playerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'DailySession';
                    readonly columns: readonly ['playerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Player';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Event: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly day: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly exchangeId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly movieId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly payload: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                };
                readonly playerId: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly type: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Event_day_type_idx_a1a328d3';
                  readonly prefix: 'Event_day_type_idx';
                  readonly columns: readonly ['day', 'type'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Event_exchangeId_idx_e449c212';
                  readonly prefix: 'Event_exchangeId_idx';
                  readonly columns: readonly ['exchangeId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Event_movieId_idx_8cb9f9db';
                  readonly prefix: 'Event_movieId_idx';
                  readonly columns: readonly ['movieId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Event_playerId_idx_710cf1aa';
                  readonly prefix: 'Event_playerId_idx';
                  readonly columns: readonly ['playerId'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Event';
                    readonly columns: readonly ['playerId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Player';
                    readonly columns: readonly ['id'];
                  };
                },
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Event';
                    readonly columns: readonly ['exchangeId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'MovieExchange';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Movie: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly genre: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly runtime: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly status: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'DRAFT'>;
                  };
                };
                readonly tier: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/int4@1', 2>;
                  };
                };
                readonly title: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly updatedAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly year: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'Movie_status_idx_e98638ab';
                  readonly prefix: 'Movie_status_idx';
                  readonly columns: readonly ['status'];
                  readonly unique: false;
                },
                {
                  readonly name: 'Movie_tier_idx_4627c10f';
                  readonly prefix: 'Movie_tier_idx';
                  readonly columns: readonly ['tier'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [];
            };
            readonly MovieExchange: {
              columns: {
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly isFixed: {
                  readonly nativeType: 'bool';
                  readonly codecId: 'pg/bool@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/bool@1', false>;
                  };
                };
                readonly lines: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                };
                readonly minute: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly movieId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly poolRank: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: true;
                };
                readonly tier: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [];
              indexes: readonly [
                {
                  readonly name: 'MovieExchange_movieId_idx_8cb9f9db';
                  readonly prefix: 'MovieExchange_movieId_idx';
                  readonly columns: readonly ['movieId'];
                  readonly unique: false;
                },
                {
                  readonly name: 'MovieExchange_movieId_minute_idx_e05126ce';
                  readonly prefix: 'MovieExchange_movieId_minute_idx';
                  readonly columns: readonly ['movieId', 'minute'];
                  readonly unique: false;
                },
              ];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'MovieExchange';
                    readonly columns: readonly ['movieId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Movie';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly MovieOptions: {
              columns: {
                readonly distractors: {
                  readonly nativeType: 'json';
                  readonly codecId: 'pg/json@1';
                  readonly nullable: false;
                };
                readonly movieId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['movieId'] };
              uniques: readonly [];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'MovieOptions';
                    readonly columns: readonly ['movieId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Movie';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
            readonly Player: {
              columns: {
                readonly createdAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly email: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: true;
                };
                readonly id: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                };
                readonly lastSeenAt: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                  readonly default: { readonly kind: 'function'; readonly expression: 'now()' };
                };
                readonly provider: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'GUEST'>;
                  };
                };
                readonly timezone: {
                  readonly nativeType: 'text';
                  readonly codecId: 'pg/text@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'literal';
                    readonly value: DefaultLiteralValue<'pg/text@1', 'UTC'>;
                  };
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [{ readonly columns: readonly ['email'] }];
              indexes: readonly [];
              foreignKeys: readonly [];
            };
            readonly ScheduleEntry: {
              columns: {
                readonly day: {
                  readonly nativeType: 'timestamptz';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                  readonly nullable: false;
                };
                readonly id: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                  readonly default: {
                    readonly kind: 'function';
                    readonly expression: 'autoincrement()';
                  };
                };
                readonly movieId: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
                readonly position: {
                  readonly nativeType: 'int4';
                  readonly codecId: 'pg/int4@1';
                  readonly nullable: false;
                };
              };
              primaryKey: { readonly columns: readonly ['id'] };
              uniques: readonly [
                { readonly columns: readonly ['movieId'] },
                { readonly columns: readonly ['day', 'position'] },
              ];
              indexes: readonly [];
              foreignKeys: readonly [
                {
                  readonly source: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'ScheduleEntry';
                    readonly columns: readonly ['movieId'];
                  };
                  readonly target: {
                    readonly namespaceId: 'public' & NamespaceId;
                    readonly tableName: 'Movie';
                    readonly columns: readonly ['id'];
                  };
                },
              ];
            };
          };
          readonly valueSet: {
            readonly AuthProvider: {
              readonly kind: 'valueSet';
              readonly values: readonly ['GUEST', 'GOOGLE', 'EMAIL'];
            };
            readonly EventType: {
              readonly kind: 'valueSet';
              readonly values: readonly [
                'TAP',
                'GUESS',
                'SHARE',
                'ROUND_COMPLETE',
                'SESSION_COMPLETE',
              ];
            };
            readonly ExchangeTier: {
              readonly kind: 'valueSet';
              readonly values: readonly ['ICONIC', 'MEDIUM', 'DEEPCUT'];
            };
            readonly MovieStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['DRAFT', 'APPROVED'];
            };
            readonly SessionStatus: {
              readonly kind: 'valueSet';
              readonly values: readonly ['IN_PROGRESS', 'FINISHED'];
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'postgres';
  readonly targetFamily: 'sql';
  readonly roots: {
    readonly Attempt: { readonly namespace: 'public' & NamespaceId; readonly model: 'Attempt' };
    readonly DailySession: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'DailySession';
    };
    readonly Event: { readonly namespace: 'public' & NamespaceId; readonly model: 'Event' };
    readonly Movie: { readonly namespace: 'public' & NamespaceId; readonly model: 'Movie' };
    readonly MovieExchange: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'MovieExchange';
    };
    readonly MovieOptions: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'MovieOptions';
    };
    readonly Player: { readonly namespace: 'public' & NamespaceId; readonly model: 'Player' };
    readonly ScheduleEntry: {
      readonly namespace: 'public' & NamespaceId;
      readonly model: 'ScheduleEntry';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly public: {
        readonly models: {
          readonly Attempt: {
            readonly fields: {
              readonly correct: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly finishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly freeTapsUsed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly guess: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly movieId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly reveals: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly score: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
            };
            readonly relations: {
              readonly movie: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Movie';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['movieId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly session: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DailySession';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['sessionId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Attempt';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly correct: { readonly column: 'correct' };
                readonly createdAt: { readonly column: 'createdAt' };
                readonly finishedAt: { readonly column: 'finishedAt' };
                readonly freeTapsUsed: { readonly column: 'freeTapsUsed' };
                readonly guess: { readonly column: 'guess' };
                readonly id: { readonly column: 'id' };
                readonly movieId: { readonly column: 'movieId' };
                readonly reveals: { readonly column: 'reveals' };
                readonly score: { readonly column: 'score' };
                readonly sessionId: { readonly column: 'sessionId' };
                readonly updatedAt: { readonly column: 'updatedAt' };
              };
            };
          };
          readonly DailySession: {
            readonly fields: {
              readonly day: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly finishedAt: {
                readonly nullable: true;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly ordinal: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly playerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly score: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly attempts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Attempt';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['sessionId'];
                };
              };
              readonly player: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Player';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['playerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'DailySession';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly day: { readonly column: 'day' };
                readonly finishedAt: { readonly column: 'finishedAt' };
                readonly id: { readonly column: 'id' };
                readonly ordinal: { readonly column: 'ordinal' };
                readonly playerId: { readonly column: 'playerId' };
                readonly score: { readonly column: 'score' };
                readonly status: { readonly column: 'status' };
              };
            };
          };
          readonly Event: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly day: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly exchangeId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly movieId: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly payload: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly playerId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly type: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly exchange: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MovieExchange';
                };
                readonly cardinality: 'N:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['exchangeId'];
                  readonly targetFields: readonly ['id'];
                };
              };
              readonly player: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Player';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['playerId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Event';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly day: { readonly column: 'day' };
                readonly exchangeId: { readonly column: 'exchangeId' };
                readonly id: { readonly column: 'id' };
                readonly movieId: { readonly column: 'movieId' };
                readonly payload: { readonly column: 'payload' };
                readonly playerId: { readonly column: 'playerId' };
                readonly type: { readonly column: 'type' };
              };
            };
          };
          readonly Movie: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly genre: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly runtime: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly tier: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly title: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly year: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly attempts: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Attempt';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['movieId'];
                };
              };
              readonly exchanges: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MovieExchange';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['movieId'];
                };
              };
              readonly options: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'MovieOptions';
                };
                readonly cardinality: '1:1';
                readonly nullable: true;
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['movieId'];
                };
              };
              readonly schedule: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'ScheduleEntry';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['movieId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Movie';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly genre: { readonly column: 'genre' };
                readonly id: { readonly column: 'id' };
                readonly runtime: { readonly column: 'runtime' };
                readonly status: { readonly column: 'status' };
                readonly tier: { readonly column: 'tier' };
                readonly title: { readonly column: 'title' };
                readonly updatedAt: { readonly column: 'updatedAt' };
                readonly year: { readonly column: 'year' };
              };
            };
          };
          readonly MovieExchange: {
            readonly fields: {
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly isFixed: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/bool@1' };
              };
              readonly lines: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly minute: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly movieId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly poolRank: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly tier: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly events: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['exchangeId'];
                };
              };
              readonly movie: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Movie';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['movieId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'MovieExchange';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly id: { readonly column: 'id' };
                readonly isFixed: { readonly column: 'isFixed' };
                readonly lines: { readonly column: 'lines' };
                readonly minute: { readonly column: 'minute' };
                readonly movieId: { readonly column: 'movieId' };
                readonly poolRank: { readonly column: 'poolRank' };
                readonly tier: { readonly column: 'tier' };
              };
            };
          };
          readonly MovieOptions: {
            readonly fields: {
              readonly distractors: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/json@1' };
              };
              readonly movieId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly movie: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Movie';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['movieId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'MovieOptions';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly distractors: { readonly column: 'distractors' };
                readonly movieId: { readonly column: 'movieId' };
              };
            };
          };
          readonly Player: {
            readonly fields: {
              readonly createdAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly email: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly lastSeenAt: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly provider: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
              readonly timezone: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/text@1' };
              };
            };
            readonly relations: {
              readonly events: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Event';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['playerId'];
                };
              };
              readonly sessions: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'DailySession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['id'];
                  readonly targetFields: readonly ['playerId'];
                };
              };
            };
            readonly storage: {
              readonly table: 'Player';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly createdAt: { readonly column: 'createdAt' };
                readonly email: { readonly column: 'email' };
                readonly id: { readonly column: 'id' };
                readonly lastSeenAt: { readonly column: 'lastSeenAt' };
                readonly provider: { readonly column: 'provider' };
                readonly timezone: { readonly column: 'timezone' };
              };
            };
          };
          readonly ScheduleEntry: {
            readonly fields: {
              readonly day: {
                readonly nullable: false;
                readonly type: {
                  readonly kind: 'scalar';
                  readonly codecId: 'pg/timestamptz-temporal@1';
                };
              };
              readonly id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly movieId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
              readonly position: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'pg/int4@1' };
              };
            };
            readonly relations: {
              readonly movie: {
                readonly to: {
                  readonly namespace: 'public' & NamespaceId;
                  readonly model: 'Movie';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['movieId'];
                  readonly targetFields: readonly ['id'];
                };
              };
            };
            readonly storage: {
              readonly table: 'ScheduleEntry';
              readonly namespaceId: 'public';
              readonly fields: {
                readonly day: { readonly column: 'day' };
                readonly id: { readonly column: 'id' };
                readonly movieId: { readonly column: 'movieId' };
                readonly position: { readonly column: 'position' };
              };
            };
          };
        };
        readonly enum: {
          readonly AuthProvider: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'GUEST'; readonly value: 'GUEST' },
              { readonly name: 'GOOGLE'; readonly value: 'GOOGLE' },
              { readonly name: 'EMAIL'; readonly value: 'EMAIL' },
            ];
          };
          readonly EventType: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'TAP'; readonly value: 'TAP' },
              { readonly name: 'GUESS'; readonly value: 'GUESS' },
              { readonly name: 'SHARE'; readonly value: 'SHARE' },
              { readonly name: 'ROUND_COMPLETE'; readonly value: 'ROUND_COMPLETE' },
              { readonly name: 'SESSION_COMPLETE'; readonly value: 'SESSION_COMPLETE' },
            ];
          };
          readonly ExchangeTier: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'ICONIC'; readonly value: 'ICONIC' },
              { readonly name: 'MEDIUM'; readonly value: 'MEDIUM' },
              { readonly name: 'DEEPCUT'; readonly value: 'DEEPCUT' },
            ];
          };
          readonly MovieStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'DRAFT'; readonly value: 'DRAFT' },
              { readonly name: 'APPROVED'; readonly value: 'APPROVED' },
            ];
          };
          readonly SessionStatus: {
            readonly codecId: 'pg/text@1';
            readonly members: readonly [
              { readonly name: 'IN_PROGRESS'; readonly value: 'IN_PROGRESS' },
              { readonly name: 'FINISHED'; readonly value: 'FINISHED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {
    readonly postgres: {
      readonly distinctOn: true;
      readonly jsonAgg: true;
      readonly lateral: true;
      readonly limit: true;
      readonly orderBy: true;
      readonly returning: true;
    };
    readonly sql: {
      readonly checkConstraint: true;
      readonly defaultInInsert: true;
      readonly enums: true;
      readonly insertOnConflictSkip: true;
      readonly insertOnConflictWithoutTarget: true;
      readonly lateral: true;
      readonly returning: true;
      readonly scalarList: true;
    };
  };
  readonly extensions: {};
  readonly execution: {
    readonly executionHash: ExecutionHash;
    readonly mutations: {
      readonly defaults: readonly [
        {
          readonly onCreate: { readonly id: 'uuidv4'; readonly kind: 'generator' };
          readonly ref: {
            readonly entry: 'Player';
            readonly field: 'id';
            readonly namespace: 'public';
          };
        },
      ];
    };
  };
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = ContractWithTypeMaps<ContractBase, TypeMaps>;

export type Namespaces = Contract['storage']['namespaces'];
